### ISSUE TITLE
Package better icons

### ISSUE THREAD

**Issue by hadess** [flathub/com.synology.CloudStationBackup#1]
Those files were extract from the `Backup.icns` inside the payload inside the installer inside the installer image for the Mac version of Cloud Station backup available here:
https://archive.synology.com/download/Utility/CloudStationBackup/4.3.3-4469

Let me know if you want the exact details on how to reproduce the icon extraction, but I used `7z` to extract the dmg, then all the files were in cpio.gz or xar format.

[Backup_16x16x32](https://user-images.githubusercontent.com/769861/160299234-53ea7a0f-b21d-4362-8361-9e5631f60cbc.png)
[Backup_32x32x32](https://user-images.githubusercontent.com/769861/160299235-bb0b2423-b6e9-4859-9d52-eee0bb8d7a1c.png)
[Backup_48x48x32](https://user-images.githubusercontent.com/769861/160299236-544bc7fd-f683-4a3d-a954-fb3ce127c34c.png)
[Backup_128x128x32](https://user-images.githubusercontent.com/769861/160299237-4f38dc6a-fffb-490d-9313-76b403534ba0.png)
[Backup_256x256x32](https://user-images.githubusercontent.com/769861/160299238-6c707a7d-41d9-49af-8ecb-1061587463a5.png)
[Backup_512x512x32](https://user-images.githubusercontent.com/769861/160299239-2f6cfbb0-8fd8-4a7a-8e0f-115bc884a69e.png)

**Comment by 00EkZ8** [comment]
Icons from your issue packaged and published.
Also updated the runtime to 21.08.
Thanks.
